
apiVersion: v1
kind: Service
metadata:
  name: my-cellphone-svc
  namespace: my-cellphone
spec:
  type: NodePort
  selector:
    app: my-cellphone-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
    
