
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
  name: my-cellphone-svc
  namespace: my-cellphone
spec:
  type: NodePort
  selector:
    app: my-cellphone-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
    